apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-k8s-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: ct-k8s-test
        image: roxsross12/k8s_test_web:latest

