version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - red-10

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - red-10

networks:
  red-10:

volumes:
  db-data:
  pgadmin-data:

