version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
